
# Description of samples
samples  : samples.tsv
# Description of sequencing units (libraries, resequencing, ...)
units    : units.tsv

# Default path for generated files
out_dir  : out
tmp_dir  : tmp

n_cpus   : 12

ncbi_submit_template :
  C3   : "docs/template_C3.sbt"
  Neff : "docs/template_Neff.sbt"

containers:
  star        : "docker://cmdoret/star:2.5.4a--0"
  trinity     : "docker://biocontainers/trinityrnaseq:v2.2.0dfsg-2b1-deb_cv1"
  samtools    : "docker://biocontainers/samtools:v1.7.0_cv4"
